### PR TITLE
Bug motor overcurrent

### PR DESCRIPTION
**Pull request by JCHJones**
This pull will add a motor step function in abridge. This causes the robot to change speed by a maximum value per frame. As speed changes are limited it is now difficult to ask for a speed change that would cause an over current event.

It may still be possible by taking a joystick and twirling it in a circle as fast as possible asking for rapid left right and forward reverse commands simultaneously. However this is a useless maneuver and thus is deliberately attempting to break the robot as this does not work in auto-mode.

### CODE REVIEW

**Comment by mike-matera** [comment]
Can you tell me what problems you've seen that this fixes? 

Looking at your patches I see that you've limited the slew rate to 75 codes per frame and removed the maximum speed of 120 (now it seems to be back to 255). Do you have any data on the maximum slew rate?

**Comment by gmfricke** [comment]
@JCHJones please respond to @mike-matera's question. Thanks.

**Comment by JCHJones** [comment]
First I found a bug that needs fixing before this can be accepted

Second, this fixes a problem where the robot rapidly commands a change in direction and this causes the motors to draw larger than normal amounts of current. As a result the self-resting fuse built into the PCB trips and cuts motor power essentially freezing a robot in place until motor commands stop long enough for it to cool down and reset.

Since auto runs at 10 frames per second this limits a -255 to 255 speed change to roughly 7 frames or 7/10ths of a second. However changes to a speed of 0 will be one frame as usually after I fix the bug

**Comment by kristiana-rendon** [comment]
I will test it after the change is made. I should basically let it run for about 30 minutes and see if the rover freezes, correct?

**Comment by gmfricke** [comment]
@kristiana-rendon, yes. Be sure to test the joystick control, keyboard control, and autonomous driving.

**Pull request closed without merging**
