### PR TITLE
Startup scripts

### PR DESCRIPTION
**Pull request by jschlind411**
Created and made the startup script (deploy.sh).

### CODE REVIEW

**Comment by mike-matera** [comment]
Hi. This pull request conflicts with PR #31. @jschlind411 I'm happy to explain what's changed and why in my pull request. Please contact me on email.

**Comment by jschlind411** [comment]
Hello Mike,

Please let me know what conflicts were created so I can fix my script file.

Thanks for your time!

- Jeff

**Comment by mike-matera** [comment]
Hi Jeff! 

I have a deploy script in my PR #31. It's in `./misc/deploy_host.sh` The script is just 56 lines and works this way:

  1. You build and test your code locally, in your own workspace and manage git there. 
  2. Enable installation steps in catkin like this:
```
$ catkin --config install
```
  3. Deploy your current workspace to the rover like this: 
```
$ ./misc/deploy_host.sh <rover-name-or-ip-address>
```

The deploy script calls `catkin build`. With installation enabled the `catkin build` command creates an `./install` directory in the workspace. It contains all binaries and scripts that are required to execute the rover code. There are some advantages to doing it this way:
 
  - It only takes 44 seconds to do a clean build on my desktop compared to 5+ minutes on the swarmie.
  - The install directory in my workspace contains 22MB of stuff which copies quickly.
  - The rover name is specified on the command line so you don't have to change the script to use it.
  - Binaries on the rover are copied into the `/tmp` directory and run from there, reducing the likelihood of confusion with repository code in `/home`

**Comment by jschlind411** [comment]
Hey Mike!

That's awesome, the script I added allows the user to pull from github and
transfer files to the swarmie (also building, packaging, unpacking and
running), transferring a working local copy to a rover for use in testing,
or simply running rovers with their current Working code. All of which I
have been successful pulling and transferring code to 3 swarmies in under a
few minutes.

How can we best merge these 2 together?

Jeff


On Sep 25, 2017 9:23 AM, "Mike Matera" <notifications@github.com> wrote:

Hi Jeff!

I have a deploy script in my PR #31
<https://github.com/BCLab-UNM/SwarmBaseCode-ROS/pull/31>. It's in
./misc/deploy_host.sh The script is just 56 lines and works this way:

   1. You build and test your code locally, in your own workspace and
   manage git there.
   2. Enable installation steps in catkin like this:

$ catkin --config install


   1. Deploy your current workspace to the rover like this:

$ ./misc/deploy_host.sh <rover-name-or-ip-address>

The deploy script calls catkin build. With installation enabled the catkin
build command creates an ./install directory in the workspace. It contains
all binaries and scripts that are required to execute the rover code. There
are some advantages to doing it this way:

   - It only takes 44 seconds to do a clean build on my desktop compared to
   5+ minutes on the swarmie.
   - The install directory in my workspace contains 22MB of stuff which
   copies quickly.
   - The rover name is specified on the command line so you don't have to
   change the script to use it.
   - Binaries on the rover are copied into the /tmp directory and run from
   there, reducing the likelihood of confusion with repository code in /home

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BCLab-UNM/SwarmBaseCode-ROS/pull/36#issuecomment-331916459>,
or mute the thread

**Comment by mike-matera** [comment]
Hi Jeff

> How can we best merge these 2 together?

That's for you to decide. For mine to work there must be corresponding changes in various CMakeLists.txt files and I would appreciate it if those were merged. You should look at how mine copies the /install directory instead of the whole project. It's a lot faster.

**Comment by jschlind411** [comment]
@mike-matera 

> That's for you to decide. For mine to work there must be corresponding changes in various CMakeLists.txt files and I would appreciate it if those were merged. You should look at how mine copies the /install directory instead of the whole project. It's a lot faster.

Looking through your extensive changes, you appear to have removed a lot of used code from:
- README
- build.yaml
- config.yaml
- package.xml's from
  + abridge
  + behaviours
  + diagnostics
  + gazebo_plugins
  + obstacle_detection
  + rqt_rover_gui
  + sbridge
  + ublox_gps
  + ublox_msgs
  + ublox_serialization
  + rover_onboard_node_launch

- added a deploy_host.sh script

Now , first off, I am coming in to this completely blind trying to sort through your extensive removal of code.  if I am reading this right you are merely transferring the necessary files for the rover to run.  How does this work with the real rovers?  Are simulated rovers effected by this?

Secondly, you are renaming the workspace to rover_workspace by default.  Is that subject to change?

I cannot merge my code with yours due to extensive changes to, or the now completely hollow, rover_onboard_node_launch script.  Is it necessary to gut the entire script in your code?

As per the name, I don't think deploy.sh and deploy_hosts.sh should create any conflicts.

@gmfricke 
I am unsure which route you wish to take.  The script I wrote uses all existing code and implements the existing rover_onboard_node script as it sits in master currently.  As per the issue with the apriltags_ros dependancy, it was added because of an issue when transferring files onto a swarmie.  The issue has since been resolved and is extraneous.  I am removing it from the pull request.

**Comment by mike-matera** [comment]
@jschlind411 Please ignore all changes in `.catkin_tools`. All of the files in there are generated and the pull request adds that directory to `.gitignore` as it should be. Which means they won't pollute commits ever again. Yay! 

The central changes are:

  1. Add the `misc/deploy_host.sh` script 
  2. Modify `launch/swarmie.launch` to support both simulated and physical launch profiles. 
  3. Cut a bunch of code out of `misc/rover_onboard_node_lauch.sh` because we can use `swarmie.launch` instead. 
  4. Modify a bunch of CMakeLists.txt files to add install commands. 

 Sorry for the confusion with all the XMLs. Couldn't be helped until `.gitignore` is fixed! Happy hacking.

**Pull request merged**
