### PR TITLE
Added New Libraries, Script File, and Calibration Code

### PR DESCRIPTION
**Pull request by kristiana-rendon**
=======================================================
Added the do_cal.py to /misc. Added the CabrilloCalibrator sketch to the /Swarmathon-Arduino folder. Added /ros_lib amd /lsm303-arduino to /Swarmathon-Arduino/libraries. The purpose of these changes are to combine new calibration code into our repo with the proper dependencies.

### CODE REVIEW

**Comment by kristiana-rendon** [comment]
Will do, thank you for letting me know!

On Feb 26, 2018 10:19 PM, "darrenchurchill" <notifications@github.com>
wrote:

Hi, can you grab the most recent version of CabrilloCalibrator.ino from our
repository? The version you have in here had a few issues. Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BCLab-UNM/SwarmBaseCode-ROS/pull/179#issuecomment-368750839>,
or mute the thread

**Comment by darrenchurchill** [comment]
Great, also, that version of the Arduino sketch no longer outputs a register value used for debugging, so you need to change line 46 of do_cal.py to reflect that:

https://github.com/BCLab-UNM/SwarmBaseCode-ROS/blob/calibration-file-arrangements/misc/do_cal.py#L46

Should be:
`logfile.write('{}, {}, {}, {}, {}, {}, {}, {}\n'.format(*data.data))`

Only eight values, instead of nine.

**Comment by kristiana-rendon** [comment]
Understood, I'll push that change right now. Thank you again!

**Comment by darrenchurchill** [comment]
Awesome thanks!

**Comment by kristiana-rendon** [comment]
No problem!

**Comment by gmfricke** [comment]
Don't forget to rename do_cal.py to calibrate.py.

**Comment by gmfricke** [comment]
Why do we need ros_serial when we can read the USB directly? I am worried about adding 42k lines just to read USB. We don't need the ROS integration to write the extended calibration file.

**Comment by kristiana-rendon** [comment]
The calibration has been tested and works just as expected. There are no issues with running the rovers either.

**Pull request merged**
