### PR TITLE
Changes that allow host compiled binaries to be deployed directly to the rover.

### PR DESCRIPTION
**Pull request by mike-matera**
This pull request creates a build flow that improves the development cycle by allowing users to host compile binaries then deploy them to the rovers. The deployment is done over SSH. Here's what changed:

  1. The CMakeLists.txt in most packages has been updated to support installation through catkin. Installation must be turned on like this:

```bash
catkin config --install
``` 

  2. The ``launch/swarmie.launch`` configuration has been improved to work for both simulated and physical rovers. The launch configuration takes an argument to specify which. If no argument is given it assumes simulation (which maintains compatibility with the existing simulation flow). 
  3. The ``misc/rover_onboard_node_launch.sh`` has been greatly reduced now that it only needs to run roslaunch. 

Here are some problems that you might find with this code and might need tweaking:

  1. The code assumes that the username on each robot is 'robot' and that SSH keys are installed. 
  2. This change conflicts with pull request #27 because the redirects are no longer used. However, roslaunch keeps log files in the ``~/.ros`` directory and this is probably the better way to do per-node logging. 

This process could probably be enhanced by using roslaunch's built-in remote launching capability.

### CODE REVIEW

**Comment by JCHJones** [comment]
It is indeed much preferred to have logging in the logs file as this is where the logs for simulated rovers currently go. It also probably fixes the issues with not catching couts that happen early in the programs life such as main before rosspin.

A unified launch file is also a win.

**Comment by gmfricke** [comment]
@jschlind411 , you should compare Mikes pull request with the scripts we have written. Take the best of both and create a new pull request.

**Comment by mike-matera** [comment]
Hello! The latest commit removes hard-coded references to ~/rover_workspace and makes the work directory relocatable.

**Comment by jschlind411** [comment]
Hey mike,

I am trying to run your code however I have been getting a few errors.

1.)  I fixed the issue you said you had with assuming the robots names are robot.  I changed them to swarmie.  That is working

2.)  your deploy_hosts.sh script works up until the rover_onboard_node_launch.sh script is called.  On line 28 (the last line) of rover_onboard_node_launch.sh see's you calling roslaunch with name:=$(hostname)

what are you trying to pass to roslaunch?  Regardless, it is creating an error:

"cannot resolve host address for machine [localhost]
The traceback for the exception was written to the log file"

I cannot do anything past this point and have been trying to debug this for a while and simply cannot get the issue to go away.  Are you trying to pass the rovers hostname into the swarmie.launch or are you trying to pass in the workstations hostname?  The current one seems to be feeding it the local(swarmie) hostname and is giving errors.  Any help with this issue would be greatly appreciated!

I have been trying to resolve this issue so I can blend our 2 sections of code together and create a fast and easy end-user experience.

**Comment by mike-matera** [comment]
I assume that the hostname is set on the rovers. We have three rovers, lovelace, maverick and element618. If you run the ``hostname`` command on them they will return their name. It seems like your rovers have the hostname set to ``localhost`` which, of course, won't work for communicating over the network. 

How do your swarmies know their names?

**Comment by jschlind411** [comment]
Hey Mike,

We go through and edit the hostname file in /etc/hostname and set up static
ip's associated with each rover.

**Comment by mike-matera** [comment]
What happens when you run the `hostname` command on the terminal prompt? 

Also, please pull my latest commits. There was a flaw in the build instructions that I missed because I had old stuff in my `.catkin_tools` directory.

**Comment by jschlind411** [comment]
Hey Mike,

If I type just hostname I get an empty string, if I use $HOSTNAME I get the
rovers name. I tried feeding that in as well with a similar error.

Jeff

**Comment by mike-matera** [comment]
You have a configuration error. Check `/etc/hostname` 

```bash
robot@maverick:~$ cat /etc/hostname 
maverick
robot@maverick:~$ 
```

After updating `/etc/hostname` you must either reboot or run this command: 

```bash
$ sudo hostname <enter-your-hostname-here>
```

**Comment by jschlind411** [comment]
@mike-matera 

I finally got the issue fixed.  The localhost IP address got fudged somehow and an extra digit was somehow applied.  After that it seemed to work ok.  Maybe build that failsafe into the script?

Currently I am not receiving any map data.  I have rebooted the rover and the problem persists.
rosnode list shows the node is published however no data is being shown in the gui.

I will continue to debug and let you know if I am successful.

**Comment by gmfricke** [comment]
Thank you, Mike. I emailed you privately expressing our gratitude for this code. We are going to take it apart and add it to our repository one piece at a time. In the meantime, I am closing this pull request.

**Pull request closed without merging**
