### PR TITLE
Throttle by default

### PR DESCRIPTION
**Pull request by abbypribis**
Addresses issue #222

### CODE REVIEW

**Comment by wfvining** [comment]
Should experiment with making message rate for camera faster.

**Comment by abbypribis** [comment]
Added demo mode option with faster frame rate and changed frame rate in simulation to 10 hz

**Comment by gmfricke** [comment]
@wfvining Awesome that you're working on this!

**Comment by wfvining** [comment]
@gmfricke Is there anything else you need before this can be merged?

**Pull request merged**
